CREATE TABLE "Cities" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	INTEGER NOT NULL UNIQUE,
	"CountryId"	INTEGER NOT NULL,
	FOREIGN KEY("CountryId") REFERENCES "Countries"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
)