CREATE TABLE "Buyers" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"FullName"	TEXT NOT NULL,
	"Gender"	TEXT,
	"CityId"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("CityId") REFERENCES "Cities"("Id")
)